language: python
env:
  global:
    - FLASK_APP=app.py
    - FLASK_DEBUG=1
    - SECRET_KEY="not-so-secret"
matrix:
  include:
    - python: 3.7
      dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - flask lint
script:
  - pytest --cov=spell_check
after_script:
  - codecov
